### ISSUE TITLE
Log output for "Test command" is shown without window chrome

### ISSUE THREAD

**Issue by ZenithDK** [KenV99/service.kodi.callbacks#4]
When I press "Test command" it pops up the debug output in the middle of the screen, on top of the current "Events" text - there's no window behind the output so it overlays the existing window in a way that makes it hard to read.

**Comment by KenV99** [comment]
What version of Kodi are you using?

**Comment by ZenithDK** [comment]
Kodi 17.0 from git.

**Comment by KenV99** [comment]
I fixed this particular issue and created a new branch 'Krypton' for this and future Krypton specific updates. If you do get around to check it and it resolves the chrome issue, please either let me know or close the issue. Thx.

**Comment by ZenithDK** [comment]
Sorry that I didn't get back to you on this, I forgot about it. Thanks for fixing the issue!
